# Generated by Django 5.1.1 on 2024-10-06 10:21

import userapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='carbon_user-avatar.svg', upload_to=userapp.models.user_directory_path),
        ),
    ]
