# Generated by Django 5.1.1 on 2024-10-06 19:39

import userapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='userapp/default_avatar.webp', upload_to=userapp.models.user_directory_path),
        ),
    ]
