# Generated by Django 5.1.1 on 2024-10-07 15:15

import django.core.validators
import mainapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_actmovie_funmovie_sadmovie_topmovie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='desc_img',
            field=models.ImageField(default='userapp/default_avatar.webp', upload_to=mainapp.models.movie_desc_directory_path, validators=[django.core.validators.FileExtensionValidator(['webp'])]),
        ),
        migrations.AlterField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='userapp/default_avatar.webp', upload_to=mainapp.models.movie_directory_path, validators=[django.core.validators.FileExtensionValidator(['webp'])]),
        ),
    ]
